# ===============================
# POSTGRESQL CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/masterforge_db
spring.datasource.username=postgres
spring.datasource.password=1234

# ===============================
# HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# SERVER PORT
# ===============================
server.port=8080