# ===============================
# CONFIGURACIÓN DE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/masterforge_db
spring.datasource.username=postgres
spring.datasource.password=1234

# ===============================
# MAGIA DE HIBERNATE (Generación automática de tablas)
# ===============================
# 'update' hace que Spring lea tu código Kotlin y cree las tablas si no existen.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=8080    